version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_USER=sofiia
      - POSTGRES_DB=dbkurs
